name: Upload Kesyon to Firebase

on:
  push:
    paths:
      - 'kesyon.json'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kòd la
        uses: actions/checkout@v3

      - name: Enstale Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Enstale Depandans
        run: npm install firebase-admin

      - name: Lanse Script Upload la
        run: node upload.js
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
